var api = {};

/*--var politicos = [
        {
            _id: 1,
            nome: 'Tarcisio Motta',
            foto: 'http://www.camara.rj.gov.br/images/foto_VEREADOR/tarcisio_motta_gd326.jpg',
            partido: 'PSOL'
        },
        {
            _id: 2,
            nome: 'Cesar Maia',
            foto: 'http://divulgacandcontas.tse.jus.br/divulga/rest/v1/candidatura/buscar/foto/2/190000005654/60011?x=1480557600000',
            partido: 'DEM'
        },
    ];
    
    --*/


var politicos =   [{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "VERÔNICA COSTA",
    "nome_urna": "VERÔNICA COSTA",
    "cargo": "VEREADOR",
    "id": 15002,
    "doacoes": [
        {"nome_doador": "MARIO ANTUNES",
        "valor_doado": 20000},
        {"nome_doador": "JACIARA VITAL NEGREIROS",
        "valor_doado": 16000},
        {"nome_doador": "DIEGO ELIAS VITAL FERREIRA",
        "valor_doado": 10000},
        {"nome_doador": "GABRIEL ALVES DE OLIVEIRA",
        "valor_doado": 10000},
        {"nome_doador": "PAULA BARROS MAIA",
        "valor_doado": 9000},
        {"nome_doador": "JONATAN SILVA DE LIMA",
        "valor_doado": 9000},
        {"nome_doador": "PAULO HENRIQUE RODRIGUES DE BARROS",
        "valor_doado": 1500},
        {"nome_doador": "CAROLINE BARBOSA DA SILVA",
        "valor_doado": 1500},
        {"nome_doador": "VANESSA DOS SANTOS",
        "valor_doado": 1500},
        {"nome_doador": "FILIPE ANTONIO RAMOS DA SILVA",
        "valor_doado": 1500},
        {"nome_doador": "ANDRESSA GUERINI GALDINO",
        "valor_doado": 1500},
        {"nome_doador": "BRUNO CHAVES RIBEIRO",
        "valor_doado": 1500},
       {"nome_doador": "VERONICA CHAVES DE CARVALHO COSTA",
        "valor_doado": 1000},
        {"nome_doador": "BRUNO CHAVES RIBEIRO",
        "valor_doado": 1000}
    ],
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "21/04/1974",
    "escolaridade": "SUPERIOR INCOMPLETO",
    "ocupacao": "VEREADOR",
  },
    {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "DAVID MIRANDA",
    "nome_urna": "DAVID MIRANDA",
    "cargo": "VEREADOR",
    "id": 50500,
     "doacoes": [
       {"nome_doador": "David Michael dos Santos Miranda",
        "valor_doado": 223200},
        {"nome_doador": "Matheus Graciano Bittencourt Andrade",
        "valor_doado": 1800},
        {"nome_doador": "Wallace Patrick Salgado",
        "valor_doado": 1260},
       {"nome_doador": "Vanderlea da Silva de Aguiar",
        "valor_doado": 1260},
       {"nome_doador": "Theo Louzada Lobato",
        "valor_doado": 1260},
       {"nome_doador": "Nagela Rithyele Pereira Dantas",
        "valor_doado": 1260},
       {"nome_doador": "Julia Sprioli",
        "valor_doado": 1260},
       {"nome_doador": "Nathalia Miranda Diniz Neves",
        "valor_doado": 1260},
       {"nome_doador": "Juliana Toschi Selbach",
        "valor_doado": 10}
],
    "partido": "PSOL",
    "situacao": "Deferido",
    "coligacao": "PSOL",
    "nascimento": "10/05/1985",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "JORNALISTA E REDATOR",
  },
     {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ALEXANDRE ISQUIERDO MOREIRA",
    "nome_urna": "ALEXANDRE ISQUIERDO",
    "cargo": "VEREADOR",
    "id": 25025,
    "doacoes": [
       {"nome_doador": "Democratas - Diretorio Nacional",
        "valor_doado": 300000},
       {"nome_doador": "Diretorio Municipal do Partido do Movimento Democratico Brasileiro - PMDB - RJ",
        "valor_doado": 1500}
],
    "partido": "DEM",
    "situacao": "Deferido",
    "coligacao": "DEM",
    "nascimento": "31/07/1972",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JOSÉ INALDO FERNANDES DA SILVA",
    "nome_urna": "INALDO SILVA",
    "cargo": "VEREADOR",
    "id": 10567,
    "doacoes": [
       {"nome_doador": "Eleição 2016 Marcelo Bezerra Crivella Prefeito",
        "valor_doado": 74809.50},
       {"nome_doador": "Luis Paulo Gomes",
        "valor_doado": 500}
],
    "partido": "PRB",
    "situacao": "Deferido",
    "coligacao": "PRB",
    "nascimento": "08/12/1964",
    "escolaridade": "ENSINO FUNDAMENTAL INCOMPLETO",
    "ocupacao": "OUTROS",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "CARLO FERREIRA DE CAIADO CASTRO",
    "nome_urna": "CARLO CAIADO",
    "cargo": "VEREADOR",
    "doacoes": [
       {"nome_doador": "Democratas - Diretorio Nacional",
        "valor_doado": 50000},
       {"nome_doador": "Carlos Eduardo de Sa Baptista",
        "valor_doado": 35000},
       {"nome_doador": "Carlos Ferreira de Caiado Castro",
        "valor_doado": 30000},
       {"nome_doador": "Ruben Ferreira",
        "valor_doado": 15000},
       {"nome_doador": "Julcinea Ferreira de Caiado Castro",
        "valor_doado": 6000},
       {"nome_doador": "Diretorio Municipal do Partido do Movimento Democratico Brasileiro - PMDB - RJ",
        "valor_doado": 2242},
       {"nome_doador": "Avelino de Campos Ribeiro",
        "valor_doado": 200},
       {"nome_doador": "Paulo Roberto Zaib Antonio",
        "valor_doado": 200}
],
    "id": 25622,
    "partido": "DEM",
    "situacao": "Deferido",
    "coligacao": "DEM",
    "nascimento": "09/01/1981",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "CARLOS NANTES BOLSONARO",
    "nome_urna": "CARLOS BOLSONARO",
    "doacoes": [
       {"nome_doador": "Jair Messias Bolsonaro",
        "valor_doado": 23500},
       {"nome_doador": "Carlos Nantes Bolsonaro",
        "valor_doado": 15100},
       {"nome_doador": "Jorge Francisco",
        "valor_doado": 2500},
       {"nome_doador": "Alessandra Ramos Cunha",
        "valor_doado": 1500}
],
    "cargo": "VEREADOR",
    "id": 20120,
    "partido": "PSC",
    "situacao": "Deferido",
    "coligacao": "PSC",
    "nascimento": "07/12/1982",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "CESAR EPITÁCIO MAIA",
    "nome_urna": "CESAR MAIA",
    "cargo": "VEREADOR",
    "doacoes": [
       {"nome_doador": "Democratas - Diretorio Nacional",
        "valor_doado": 342000},
       {"nome_doador": "Miguel Barros Henrique",
        "valor_doado": 4000}
],
    "id": 25500,
    "partido": "DEM",
    "situacao": "Deferido",
    "coligacao": "DEM",
    "nascimento": "18/06/1945",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "ECONOMIA",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JOAO FRANCISCO INACIO BRAZAO",
    "nome_urna": "CHIQUINHO BRAZÃO",
    "cargo": "VEREADOR",
     "doacoes": [
       {"nome_doador": "Joao Francisco Inacio Brazao",
        "valor_doado": 100000},
       {"nome_doador": "Maria Magdala Tolentino",
        "valor_doado": 20000}
],
    "id": 15101,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "22/02/1962",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "CLAUDIO BONFIM DE CASTRO E SILVA",
    "nome_urna": "CLÁUDIO CASTRO",
    "cargo": "VEREADOR",
     "doacoes": [
       {"nome_doador": "Eleição 2016 Arthur Henrique Gonçalves Ferreira Prefeito",
        "valor_doado": 261.78}
],
    "id": 20010,
    "partido": "PSC",
    "situacao": "Deferido",
    "coligacao": "PSC",
    "nascimento": "29/03/1979",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "ADVOGADO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "CARLOS EDUARDO DE MATTOS",
    "nome_urna": "DR. CARLOS EDUARDO",
    "cargo": "VEREADOR",
     "doacoes": [
       {"nome_doador": "Carlos Eduardo de Mattos",
        "valor_doado": 104000},
       {"nome_doador": "Jose Ricardo Catharino de Oliveira",
        "valor_doado": 45000},
       {"nome_doador": "Marco Antonio de Mattos",
        "valor_doado": 35000},
       {"nome_doador": "Fernando Henrique de Mattos",
        "valor_doado": 30000},
       {"nome_doador": "Ayrcea Catharino de Oliveira",
        "valor_doado": 15000},
       {"nome_doador": "Maria Abrahao Assef de Mattos",
        "valor_doado": 12500},
       {"nome_doador": "Fernando Henrique de Mattos Filho",
        "valor_doado": 10000},
       {"nome_doador": "Antonio Manoel de Souza",
        "valor_doado": 3000},
       {"nome_doador": "Tatiana Ferraz",
        "valor_doado": 2500},
       {"nome_doador": "Alexandre da Costa Peixoto",
        "valor_doado": 1500},
],
    "id": 77044,
    "partido": "SD",
    "situacao": "Deferido",
    "coligacao": "POR UM RIO SOLIDÁRIO",
    "nascimento": "18/01/1964",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "GILBERTO DE OLIVEIRA LIMA",
    "nome_urna": "DR. GILBERTO",
    "cargo": "VEREADOR",
    
    "id": 33123,
    "partido": "PMN",
    "situacao": "Deferido",
    "coligacao": "PMN",
    "nascimento": "15/09/1959",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "MEDICO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "FELIPE MICHEL",
    "nome_urna": "FELIPE MICHEL",
    "cargo": "VEREADOR",
    "doacoes": [
       {"nome_doador": "Ricardo Siqueira Rodrigues",
        "valor_doado": 10000},
       {"nome_doador": "Pericles Vasconcellos Rangel",
        "valor_doado": 5000},
       {"nome_doador": "Marcelo Guimaraes Barbosa da Silva",
        "valor_doado": 6000},
       {"nome_doador": "Alvaro Aderaldo Chaves Filho",
        "valor_doado": 5000},
       {"nome_doador": "Carlos Eduardo Fernandez Soares",
        "valor_doado": 2231.79},
       {"nome_doador": "Paulo Cesar Michel",
        "valor_doado": 2000},
       {"nome_doador": "Antonio Paiva Salgado",
        "valor_doado": 1760},
       {"nome_doador": "Alexandre Viana do Nascimento",
        "valor_doado": 1000},
       {"nome_doador": "Eldir Barroso da Silva",
        "valor_doado": 1000},
       {"nome_doador": "Sergio Ricardo Siqueira",
        "valor_doado": 1000},
       {"nome_doador": "Milene Ponce de Leon",
        "valor_doado": 1000},
       {"nome_doador": "Lucia Helena de Oliveira Alves",
        "valor_doado": 1000},
       {"nome_doador": "Juliana Furtado Carvalho",
        "valor_doado": 1000},
       {"nome_doador": "Fabiane de Sousa Silva",
        "valor_doado": 1000},
],
    "id": 45001,
    "partido": "PSDB",
    "situacao": "Deferido",
    "coligacao": "RIO DE OPORTUNIDADES E DIREITOS",
    "nascimento": "05/04/1977",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "COMERCIANTE",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ITALO PEREIRA CAMPOS",
    "nome_urna": "ITALO CIBA",
    "cargo": "VEREADOR",
    
    "id": 70669,
    "partido": "PT do B",
    "situacao": "Deferido",
    "coligacao": "União Trabalhista Cristã",
    "nascimento": "09/03/1959",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "APOSENTADO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JAIRO SOUZA SANTOS JUNIOR",
    "nome_urna": "DR. JAIRINHO",
    "cargo": "VEREADOR",
    "doacoes": [
       {"nome_doador": "Getulio Gomes de Oliveira",
        "valor_doado": 100000},
       {"nome_doador": "Jairo Souza Santos Junior",
        "valor_doado": 40000},
       {"nome_doador": "Jesse Moraes de Jesus",
        "valor_doado": 8000},
       {"nome_doador": "Jairo Souza Santos",
        "valor_doado": 5000},
       {"nome_doador": "Lucas Ferreira Burgelli",
        "valor_doado": 5000},
       {"nome_doador": "Tharsia Wanderson da Conceição",
        "valor_doado": 5000},
       {"nome_doador": "Tadeu Henrique Faria Santos",
        "valor_doado": 1000},
       {"nome_doador": "Rubens Ricardo de Castro Oliveira",
        "valor_doado": 970},
       {"nome_doador": "Roberto Ricardo de Castro Oliveira",
        "valor_doado": 970},
       {"nome_doador": "Heloisa Emilia Patricio de Andrade",
        "valor_doado": 970},
       {"nome_doador": "Jannice Maria de Rocha PItta",
        "valor_doado": 970},
       {"nome_doador": "Alexandro Alves ignacio",
        "valor_doado": 970},
       {"nome_doador": "Sheila Patricia dos Santos",
        "valor_doado": 970},
       {"nome_doador": "Luciane Beatriz Silva",
        "valor_doado": 970},
       {"nome_doador": "Marcos Antonio Barbosa de Souza",
        "valor_doado": 970},
       {"nome_doador": "Marcelo Brito Rodrigues",
        "valor_doado": 970},
       {"nome_doador": "Valtair dos Santos Ambrosio",
        "valor_doado": 970},
       {"nome_doador": "Thalita Fernandes Santos",
        "valor_doado": 970},
       {"nome_doador": "Monique Leitao da Silva",
        "valor_doado": 970},
       {"nome_doador": "Josimar Campos Azevedo",
        "valor_doado": 970},
       {"nome_doador": "Fausto Enrique Infran",
        "valor_doado": 970},
       {"nome_doador": "Deisimar mendes Capella",
        "valor_doado": 970},
       {"nome_doador": "Cristiane Izidoro de Souza",
        "valor_doado": 970},
       {"nome_doador": "Almir da Silva Filho",
        "valor_doado": 970},
       {"nome_doador": "Emilson de Oliveira Rocha",
        "valor_doado": 970},
],
    "id": 15126,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "31/12/1977",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JOÃO MENDES DE JESUS",
    "nome_urna": "JOÃO M. DE JESUS",
    "cargo": "VEREADOR",
     "doacoes": [
       {"nome_doador": "ELEICAO 2016 MARCELO BEZERRA CRIVELLA PREFEITO",
        "valor_doado": 61309.50},
       {"nome_doador": "JOAO MENDES DE JESUS",
        "valor_doado": 5000},
       {"nome_doador": "JOSE CARLOS COSTA SIMONIN",
        "valor_doado": 2000},
       {"nome_doador": "RAIMUNDA DE FATIMA GONCALVES RIBEIRO",
        "valor_doado": 800},
       {"nome_doador": "BRUNA MELO DE OLIVEIRA",
        "valor_doado": 800},
       {"nome_doador": "CARLA MELO DE OLIVEIRA MATTOS JUVENCIO",
        "valor_doado": 800},
       {"nome_doador": "ROSEMERI BENTO COUTINHO OLIVEIRA",
        "valor_doado": 800},
       {"nome_doador": "ABIGAIL DOS ANJOS SILVA",
        "valor_doado": 800},
     ],
    "id": 10123,
    "partido": "PRB",
    "situacao": "Deferido",
    "coligacao": "PRB",
    "nascimento": "27/01/1953",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JOÃO RICARDO RIBAS JÚNIOR",
    "nome_urna": "DR. JOÃO RICARDO",
    "cargo": "VEREADOR",
    "doacoes": [
       {"nome_doador": "Aron Klajnman",
        "valor_doado": 4300},
       {"nome_doador": "Joao Carlos Alves dos Santos",
        "valor_doado": 3000},
       {"nome_doador": "Diretorio Municipal do Partido do Movimento Democratico Brasileiro - PMDB - RJ",
        "valor_doado": 19141},
],
    "id": 15999,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "25/12/1964",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "MEDICO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JONES BARBOSA DE MOURA",
    "nome_urna": "JONES MOURA",
    "cargo": "VEREADOR",
    "doacoes": [
       {"nome_doador": "ELEICAO 2016 ANTONIO PEDRO INDIO PREFEITO",
        "valor_doado": 780},
    ],
    "id": 55111,
    "partido": "PSD",
    "situacao": "Deferido",
    "coligacao": "PSD",
    "nascimento": "16/06/1974",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "SERVIDOR PUBLICO MUNICIPAL",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JORGE MIGUEL FELIPPE",
    "nome_urna": "JORGE FELIPPE",
    "cargo": "VEREADOR",
    "doacoes": [
       {"nome_doador": "JORGE MIGUEL FELIPPE",
        "valor_doado": 65000},
       {"nome_doador": "ROGERIO MOREIRA VIEIRA",
        "valor_doado": 50000},
       {"nome_doador": "EDUARDO TUFFY FELIPPE FILHO",
        "valor_doado": 40000},
       {"nome_doador": "DELIO DA SILVA",
        "valor_doado": 2000},
       {"nome_doador": "EDUARDO LEMOS GONCALVES DE OLIVEIRA",
        "valor_doado": 20000},
       {"nome_doador": "LEANDRO AUGUSTO PRINCIPE DE QUEIROZ",
        "valor_doado": 16000},
       {"nome_doador": "JOAO HENRIQUE COSTA SOUZA TRISTAO",
        "valor_doado": 10000},
       {"nome_doador": "SAMIRA TUFFY FELIPPE",
        "valor_doado": 13000},
     {"nome_doador": "CARLOS SEBASTIAO GRACA COSTA",
        "valor_doado": 5000},
       {"nome_doador": "ROSANE DE SOUZA REIS DA SILVA",
        "valor_doado": 4500},
       {"nome_doador": "DIRETORIO MUNICIPAL DO PARTIDO DO MOVIMENTO DEMOCRATICO BRASILEIRO - PMDB - RJ",
        "valor_doado": 7238},
       {"nome_doador": "SANDRA REGINA RODRIGUES PINHEIRO",
        "valor_doado": 4000},
       {"nome_doador": "ROGER MARQUES ROCHA",
        "valor_doado": 4000},
       {"nome_doador": "FABIO CRISTINO",
        "valor_doado": 3200},
       {"nome_doador": "MAURA SABINO DA SILVA",
        "valor_doado": 3000},
       {"nome_doador": "BRUNO ASSIS DE LIMA",
        "valor_doado": 3000},
      {"nome_doador": "JOAO GALDINO DE MELO",
        "valor_doado": 3000},
     {"nome_doador": "JOSE DO NASCIMENTO PINHEIRO",
        "valor_doado": 3000},
       {"nome_doador": "JOAOBE SERAFIM NASCIMENTO",
        "valor_doado": 2000},
       {"nome_doador": "ALEXANDRE VIEIRA SOUZA",
        "valor_doado": 2000},
       {"nome_doador": "NOEMIA MIGUEL FELIPPE",
        "valor_doado": 1500},
       {"nome_doador": "ROSANE MARIA SANTANGELO SOUZA",
        "valor_doado": 1000},
       {"nome_doador": "SELMO RODRIGUES CARDOSO",
        "valor_doado": 1000},
       {"nome_doador": "LUIZ ALBERTO CORREA DA SILVA",
        "valor_doado": 1000},
     ],
    "id": 15800,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "02/06/1950",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "OTONI MOURA DE PAULO JUNIOR",
    "nome_urna": "OTONI DE PAULA",
    "cargo": "VEREADOR",
    
    "id": 20200,
    "partido": "PSC",
    "situacao": "Deferido",
    "coligacao": "PSC",
    "nascimento": "22/11/1976",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "OUTROS",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JORGE HENRIQUE MARTINS MANAIA",
    "nome_urna": "DR. JORGE MANAIA",
    "cargo": "VEREADOR",
    "doacoes": [
       {"nome_doador": "Marcelo Rodrigues Soares",
        "valor_doado": 15000},
       {"nome_doador": "Jorge Henrique Martins manaia",
        "valor_doado": 34000},
       {"nome_doador": "Vagner de Souza",
        "valor_doado": 900},
       {"nome_doador": "Ronizi Antunes Silva Pereira",
        "valor_doado": 900},
       {"nome_doador": "Lucas Moritz Postigo",
        "valor_doado": 900},
       {"nome_doador": "Emerson Luiz Macedo de Menezes",
        "valor_doado": 900},
       {"nome_doador": "Carlos Jose dos Santos",
        "valor_doado": 900},
       {"nome_doador": "#NULO",
        "valor_doado": 0.60},
],
    "id": 77456,
    "partido": "SD",
    "situacao": "Deferido",
    "coligacao": "SD",
    "nascimento": "07/05/1963",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "TADEU AMORIM DE BARROS JUNIOR",
    "nome_urna": "JUNIOR DA LUCINHA",
    "cargo": "VEREADOR",
    
    "id": 15620,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "16/10/1981",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "LEANDRO LYRA BRAGA DOGNINI",
    "nome_urna": "LEANDRO LYRA",
    "cargo": "VEREADOR",
    
    "id": 30300,
    "partido": "NOVO",
    "situacao": "Deferido",
    "coligacao": "NOVO",
    "nascimento": "29/08/1992",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "ESTUDANTE, BOLSISTA, ESTAGIARIO E ASSEMELHADOS",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "LUCIANA GONÇALVES DE NOVAES",
    "nome_urna": "LUCIANA NOVAES",
    "cargo": "VEREADOR",
    
    "id": 13535,
    "partido": "PT",
    "situacao": "Deferido",
    "coligacao": "RIO EM COMUM",
    "nascimento": "05/06/1983",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "ASSISTENTE SOCIAL",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "LUIS ANTONIO DA COSTA RAMOS",
    "nome_urna": "LUIZ CARLOS R. FILHO",
    "cargo": "VEREADOR",
    
    "id": 19019,
    "partido": "PTN",
    "situacao": "Deferido",
    "coligacao": "PTN",
    "nascimento": "01/12/1976",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "CORRETOR DE IMOVEIS, SEGUROS, TITULOS E VALORES",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ALEXANDRE JOSE BERARDINELLI ARRAES",
    "nome_urna": "ALEXANDRE ARRAES",
    "cargo": "VEREADOR",
    
    "id": 45000,
    "partido": "PSDB",
    "situacao": "Deferido",
    "coligacao": "PSDB",
    "nascimento": "20/08/1962",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "MEDICO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "MARCELINO ANTONIO D'ALMEIDA",
    "nome_urna": "MARCELINO D'ALMEIDA",
    "cargo": "VEREADOR",
    
    "id": 11369,
    "partido": "PP",
    "situacao": "Deferido",
    "coligacao": "PP",
    "nascimento": "05/08/1949",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "VEREADOR",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "MARCELLO MORAES SICILIANO",
    "nome_urna": "MARCELLO SICILIANO",
    "cargo": "VEREADOR",
    
    "id": 31888,
    "partido": "PHS",
    "situacao": "Deferido",
    "coligacao": "PHS",
    "nascimento": "14/08/1972",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "EMPRESARIO",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "MARCELO ARAR",
    "nome_urna": "MARCELO ARAR",
    "cargo": "VEREADOR",
    
    "id": 14000,
    "partido": "PTB",
    "situacao": "Deferido",
    "coligacao": "PTB",
    "nascimento": "06/02/1975",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "PRODUTOR DE ESPETACULOS PUBLICOS",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "MARIELLE FRANCISCO DA SILVA",
    "nome_urna": "MARIELLE FRANCO",
    "cargo": "VEREADOR",
    
    "id": 50777,
    "partido": "PSOL",
    "situacao": "Deferido",
    "coligacao": "Mudar é possível",
    "nascimento": "27/07/1979",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "SOCIOLOGO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "PAULO PINHEIRO",
    "nome_urna": "PAULO PINHEIRO",
    "cargo": "VEREADOR",
    
    "id": 50111,
    "partido": "PSOL",
    "situacao": "Deferido",
    "coligacao": "Mudar é possível",
    "nascimento": "22/01/1949",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ADALMIR D'AGUILA DE SOUZA",
    "nome_urna": "PROF. ADALMIR",
    "cargo": "VEREADOR",
    
    "id": 45779,
    "partido": "PSDB",
    "situacao": "Deferido",
    "coligacao": "PSDB",
    "nascimento": "15/05/1978",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "PROFESSOR DE ENSINO MEDIO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ROGÉRIO DE CASTRO LOPES",
    "nome_urna": "PROF. ROGÉRIO ROCAL",
    "cargo": "VEREADOR",
    
    "id": 14433,
    "partido": "PTB",
    "situacao": "Deferido",
    "coligacao": "Mudar é possível",
    "nascimento": "28/09/1975",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ELISEU GOMES KESSLER",
    "nome_urna": "ELISEU KESSLER",
    "cargo": "VEREADOR",
    
    "id": 55622,
    "partido": "PSD",
    "situacao": "Deferido",
    "coligacao": "PSD",
    "nascimento": "17/08/1968",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "FERNANDO WILLIAM FERREIRA",
    "nome_urna": "FERNANDO WILLIAM",
    "cargo": "VEREADOR",
    
    "id": 12603,
    "partido": "PDT",
    "situacao": "Deferido",
    "coligacao": "PDT",
    "nascimento": "15/05/1954",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "MEDICO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "PAULO SANTOS MESSINA",
    "nome_urna": "PAULO MESSINA",
    "cargo": "VEREADOR",
    
    "id": 90123,
    "partido": "PROS",
    "situacao": "Deferido",
    "coligacao": "PROS",
    "nascimento": "18/10/1975",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "RAFAEL ALOISIO FREITAS",
    "nome_urna": "RAFAEL A. FREITAS",
    "cargo": "VEREADOR",
    
    "id": 15123,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "12/02/1980",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "REIMONT LUIZ OTONI SANTA BARBARA",
    "nome_urna": "REIMONT",
    "cargo": "VEREADOR",
    
    "id": 13333,
    "partido": "PT",
    "situacao": "Deferido",
    "coligacao": "RIO EM COMUM",
    "nascimento": "02/09/1961",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "RENATO ATHAYDE SILVA",
    "nome_urna": "RENATO CINCO",
    "cargo": "VEREADOR",
    
    "id": 50555,
    "partido": "PSOL",
    "situacao": "Deferido",
    "coligacao": "Mudar é possível",
    "nascimento": "25/05/1974",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "SOCIOLOGO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "JOSE RENATO CARDOZO MOURA",
    "nome_urna": "RENATO MOURA",
    "cargo": "VEREADOR",
    
    "id": 12500,
    "partido": "PDT",
    "situacao": "Deferido",
    "coligacao": "PDT",
    "nascimento": "06/03/1962",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "EMPRESARIO",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ROSA MARIA ORLANDO FERNANDES",
    "nome_urna": "ROSA FERNANDES",
    "cargo": "VEREADOR",
    
    "id": 15150,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "21/05/1956",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "LEONEL BRIZOLA NETO",
    "nome_urna": "LEONEL BRIZOLA NETO",
    "cargo": "VEREADOR",
    
    "id": 50000,
    "partido": "PSOL",
    "situacao": "Deferido",
    "coligacao": "PSOL",
    "nascimento": "03/08/1975",
    "escolaridade": "SUPERIOR INCOMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "TÂNIA CRISTINA MAGALHÃES BASTOS E SILVA",
    "nome_urna": "TÂNIA BASTOS",
    "cargo": "VEREADOR",
    
    "id": 10999,
    "partido": "PRB",
    "situacao": "Deferido",
    "coligacao": "PRB",
    "nascimento": "01/01/1967",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "TARCÍSIO MOTTA DE CARVALHO",
    "nome_urna": "TARCÍSIO MOTTA",
    "cargo": "VEREADOR",
    
    "id": 50123,
    "partido": "PSOL",
    "situacao": "Deferido",
    "coligacao": "Mudar é possível",
    "nascimento": "28/01/1975",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "PROFESSOR DE ENSINO MEDIO",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "MARIA TERESA BERGHER",
    "nome_urna": "TERESA BERGHER",
    "cargo": "VEREADOR",
    
    "id": 45245,
    "partido": "PSDB",
    "situacao": "Deferido",
    "coligacao": "RIO DE OPORTUNIDADES E DIREITOS",
    "nascimento": "16/08/1948",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "THIAGO KWIATKOWSKI RIBEIRO",
    "nome_urna": "THIAGO K. RIBEIRO",
    "cargo": "VEREADOR",
    
    "id": 15159,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "21/07/1982",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ROOSEVELT BARRETO BARCELOS",
    "nome_urna": "VAL DO CEASA",
    "cargo": "VEREADOR",
    
    "id": 51888,
    "partido": "PEN",
    "situacao": "Deferido",
    "coligacao": "O RIO QUE EU QUERO",
    "nascimento": "04/05/1969",
    "escolaridade": "ENSINO FUNDAMENTAL COMPLETO",
    "ocupacao": "OUTROS",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "VERA LUCIA FERREIRA LINS",
    "nome_urna": "VERA LINS",
    "cargo": "VEREADOR",
    
    "id": 11111,
    "partido": "PP",
    "situacao": "Deferido",
    "coligacao": "PP",
    "nascimento": "29/10/1947",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  },{
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "WILLIAN CARVALHO DOS SANTOS",
    "nome_urna": "WILLIAN COELHO",
    "cargo": "VEREADOR",
    
    "id": 15040,
    "partido": "PMDB",
    "situacao": "Deferido",
    "coligacao": "PMDB",
    "nascimento": "10/11/1982",
    "escolaridade": "SUPERIOR COMPLETO",
    "ocupacao": "VEREADOR",
  }, {
    "situacao_pos_pleito": "Eleito por QP",
    "nome_completo": "ANTONIO JOSE PAPERA DE AZEVEDO",
    "nome_urna": "ZICO",
    "cargo": "VEREADOR",
    
    "id": 14012,
    "partido": "PTB",
    "situacao": "Deferido",
    "coligacao": "PTB",
    "nascimento": "28/04/1966",
    "escolaridade": "ENSINO MEDIO COMPLETO",
    "ocupacao": "VEREADOR",
  }
];
 

 


api.lista = function(req,res) {
    
    res.json(politicos);
    
};

api.buscaPorId = function(req,res) {
    
    var politico = politicos.find(function(politico){
        return politico._id == req.params.id;
    });
    req.params.id
};

module.exports = api;